// <auto-generated />
using AngularApiMain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularApiMain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231003170246_r1")]
    partial class r1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AngularApiMain.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("fooditems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Creamy lentils cooked with spices.",
                            ImageUrl = "dal_makhni.jpg",
                            Name = "Dal Makhni",
                            Rating = 4.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Paneer cooked in a rich tomato-based gravy.",
                            ImageUrl = "shahi_paneer.jpg",
                            Name = "Shahi Paneer",
                            Rating = 4.4000000000000004,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Creamy paneer dish cooked in a handi.",
                            ImageUrl = "handi_panner.jpg",
                            Name = "Handi Panner",
                            Rating = 4.5999999999999996,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fried bread with spicy chickpea curry.",
                            ImageUrl = "chole_bhature.jpg",
                            Name = "Chole Bhature",
                            Rating = 4.2000000000000002,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Soft and buttery Indian flatbread.",
                            ImageUrl = "butter_naan.jpg",
                            Name = "Butter Naan",
                            Rating = 4.2999999999999998,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Traditional Indian flatbread made with gram flour.",
                            ImageUrl = "missi_roti.jpg",
                            Name = "Missi Roti",
                            Rating = 4.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dessert made from paneer in sweet milk.",
                            ImageUrl = "rasmalai.jpg",
                            Name = "Rasmalai",
                            Rating = 4.7000000000000002,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Delicious cake for dessert.",
                            ImageUrl = "cake.jpg",
                            Name = "Cake",
                            Rating = 4.2000000000000002,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Refreshing cola drink.",
                            ImageUrl = "coke.jpg",
                            Name = "Coke",
                            Rating = 4.0,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Creamy and sweet ice cream.",
                            ImageUrl = "ice_cream.jpg",
                            Name = "IceCream",
                            Rating = 4.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Vegetarian burger with fresh veggies.",
                            ImageUrl = "veg_burger.jpg",
                            Name = "Veg Burger",
                            Rating = 4.2000000000000002,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Crispy and crunchy burger with a special sauce.",
                            ImageUrl = "crispy_burger.jpg",
                            Name = "Crispy Burger",
                            Rating = 4.0999999999999996,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Burger with cheesy goodness.",
                            ImageUrl = "chesse_burger.jpg",
                            Name = "Chesse Burger",
                            Rating = 4.2999999999999998,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Double the cheese for double the delight.",
                            ImageUrl = "double_chesse_burger.jpg",
                            Name = "Double Chesse Burger",
                            Rating = 4.4000000000000004,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Burger with delicious chicken patty.",
                            ImageUrl = "chicken_burger.jpg",
                            Name = "Chicken Burger",
                            Rating = 4.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Burger with a spicy kick of pepper.",
                            ImageUrl = "pepper_burger.jpg",
                            Name = "Pepper Burger",
                            Rating = 4.0999999999999996,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Burger with corn filling.",
                            ImageUrl = "corn_burger.jpg",
                            Name = "Corn Burger",
                            Rating = 4.2000000000000002,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Burger with roasted ingredients.",
                            ImageUrl = "roasted_burger.jpg",
                            Name = "Roasted Burger",
                            Rating = 4.2999999999999998,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Refreshing cola drink.",
                            ImageUrl = "coke.jpg",
                            Name = "Coke",
                            Rating = 4.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Delicious brownie cake for dessert.",
                            ImageUrl = "brownie_cake.jpg",
                            Name = "Brownie Cake",
                            Rating = 4.5,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Pizza with sweet corn toppings.",
                            ImageUrl = "sweetcorn_pizza.jpg",
                            Name = "SweetCorn Pizza",
                            Rating = 4.5999999999999996,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Pizza with capsicum and cheese.",
                            ImageUrl = "capsicum_pizza.jpg",
                            Name = "Capsicum Pizza",
                            Rating = 4.5,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 23,
                            Description = "Pizza with mozzarella cheese and veggies.",
                            ImageUrl = "mozeralla_cheese_pizza.jpg",
                            Name = "Mozeralla cheese pizza with veggies",
                            Rating = 4.4000000000000004,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Pizza with double cheese burst.",
                            ImageUrl = "double_cheeseburst_pizza.jpg",
                            Name = "Double CheeseBurst Pizza",
                            Rating = 4.5999999999999996,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 25,
                            Description = "Pizza with paneer toppings.",
                            ImageUrl = "paneer_pizza.jpg",
                            Name = "Paneer Pizza",
                            Rating = 4.2999999999999998,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Classic Margherita pizza with tomatoes and basil.",
                            ImageUrl = "margherita_pizza.jpg",
                            Name = "Margherita pizza",
                            Rating = 4.2000000000000002,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Pizza with cheesy chicken and pasta toppings.",
                            ImageUrl = "cheesy_chicken_pasta_pizza.jpg",
                            Name = "Cheesy chicken pasta pizza",
                            Rating = 4.5,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Refreshing cola drink.",
                            ImageUrl = "coke.jpg",
                            Name = "Coke",
                            Rating = 4.0,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 29,
                            Description = "Molten lava cake for dessert.",
                            ImageUrl = "lava_cake.jpg",
                            Name = "Lava Cake",
                            Rating = 4.7000000000000002,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 30,
                            Description = "Creamy and sweet ice cream.",
                            ImageUrl = "ice_cream.jpg",
                            Name = "IceCream",
                            Rating = 4.4000000000000004,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("AngularApiMain.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("restaurants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Since 1978, Eat Sweet and Talk Sweetly.",
                            ImageUrl = "https://i.pinimg.com/originals/7d/74/19/7d7419496c7c143aadfbcffcfd6c2812.png",
                            Name = "Radhika",
                            Rating = 4.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Be A King Like Burger King.",
                            ImageUrl = "https://www.shutterstock.com/shutterstock/photos/2129642369/display_1500/stock-photo-amsterdam-netherlands-feb-burger-set-from-burger-king-restaurant-burger-king-s-2129642369.jpg",
                            Name = "Burger King",
                            Rating = 4.0,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "It's All About Domino's Pizza.....",
                            ImageUrl = "https://smartcanucks.ca/wp-content/uploads/2015/12/dominos-pizza.jpg",
                            Name = "Dominos",
                            Rating = 4.2000000000000002,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("AngularApiMain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AngularApiMain.Models.FoodItem", b =>
                {
                    b.HasOne("AngularApiMain.Models.Restaurant", null)
                        .WithMany("FoodItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AngularApiMain.Models.Restaurant", b =>
                {
                    b.Navigation("FoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
